export const Profile = [
    {
        "category": "Web Development",
        "keywords": [
          ["Programmer"],
          ["Developer"],
          ["Coder"],
          ["Backend"],
          ["Frontend"],
          ["Back end"],
          ["Front end"],
          ["Web", "Developer"],
          ["Web", "Engineer"],
          ["SEO"],
          ["Python"],
          ["PHP"],
          ["JavaScript"],
          ["React"],
          ["ReactJS"],
          ["JS"],
          ["Java"],
          ["HTML"],
          ["CSS"],
          ["C#"],
          ["C++"],
        ]
      },
      {
        "category": "Mobile Development",
        "keywords": [
          ["Programmer"],
          ["Developer"],
          ["Coder"],
          ["Objective C"],
          ["Swift"],
          ["Java"],
          ["iOS"],
          ["Android"],
          ["Phonegap"],
          ["React Native"],
        ]
      },
      {
        "category": "Data Science",
        "keywords": [
          ["Machine", "Learning"],
          ["Deep", "Learning"],
          ["Analytics"],
          ["Analyst"],
          ["Algebra"],
          ["Probability", "theory"],
          ["Statistics"],
          ["Math"],
          ["Mathematician"],
          ["Tensorflow"],
          ["Theano"],
          ["Torch"],
          ["MXNet"],
          ["scikit"],
          ["Azure ML"],
          ["ML Studio"],
        
        ]
      },
      {
        "category": "Design",
        "keywords": [
          ["Design"],
          ["UI"],
          ["UX"],
          ["Logo"],
          ["Illustrator"],
          ["Illustration"],
          ["Artist"],
          ["User", "Interface"],
          ["User", "Experience"],
          ["Photoshop"],
          ["Sketch"],
          ["InDesign"],
          ["Adobe"]
        ]
      },
      {
        "category": "Public Relations",
        "keywords": [
          ["CEO"],
          ["Chief Executive Officer"],
          ["Communications"],
          ["Marketing"],
          ["Brand"],
          ["Branding"],
          ["Content", "Manager"],
          ["Content", "Strategist"],
          ["Copy", "Writer"],
          ["Public", "Affairs"],
          ["Public", "Relations"],
          ["Event", "Coordinator"],
          ["Event", "Manager"],
          ["Social", "Media"],
          ["Media", "Director"],
          ["Media", "Coordinator"],
          ["Relationship", "Manager"],
          ["Media", "Relations"],
          ["Media", "Coordinator"],
          ["Media", "Director"],
          ["Media", "Specialist"]
        ]
      },
      {
        "category": "Marketing",
        "keywords": [
          ["CEO"],
          ["Chief Executive Officer"],
          ["Marketing"],
          ["Marketer"],
          ["Account", "Coordinator"],
          ["Account", "Executive"],
          ["Advertising"],
          ["Ads"],
          ["Advert"],
          ["Art", "Director"],
          ["Assistant", "Director"],
          ["Brand"],
          ["Branding"],
          ["Product", "Manager"],
          ["Business", "Development"],
          ["Communications"],
          ["Content", "Manager"],
          ["Content", "Writer"],
          ["Community", "Manager"],
          ["Copywriter"],
          ["Creative", "Assistant"],
          ["Creative", "Director"],
          ["Market", "Research"],
          ["Media", "Assistant"],
          ["Media", "Buyer"],
          ["Media", "Director"],
          ["Media", "Planner"],
          ["Media", "Researcher"],
          ["Media", "Relations"],
          ["Promotion"],
          ["Promotions"],
          ["Public", "Relations"],
          ["Publicity"],
          ["SEO"],
          ["Ecommerce"],
          ["E commerce"],
          ["PMM"]
        ]
      },
      {
        "category": "Human Resources",
        "keywords": [
          ["HR"],
          ["Human Resources"],
          ["Talent"],
          ["Recruiter"],
          ["Recruiting"],
          ["Administrative"],
          ["Employee", "Relations"],
          ["HRD"],
          ["Sourcing"],
          ["Staffing"]
        ]
      },
      {
        "category": "Sales & Business Development",
        "keywords": [
          ["CEO"],
          ["Chief Executive Officer"],
          ["Sales"],
          ["Salesperson"],
          ["Salesman"],
          ["Dealer"],
          ["Business", "Development"],
          ["Business", "Manager"],
          ["Market", "Development"],
          ["Account", "Manager"],
          ["Account", "Director"],
          ["Account", "Representative"],
          ["Client", "Relationship"],
          ["Customer", "Relationship"],
          ["Customer", "Success"],
          ["Customer", "Care"],
          ["Telesales"],
          ["Brand", "Ambassador"],
          ["Industry", "Representative"],
          ["Retail"]
        ]
      },
      {
        "category": "Finance & Accounting",
        "keywords": [
          ["Accounting"],
          ["Accountant"],
          ["Financial"],
          ["Finance"],
          ["Auditor"],
          ["Audit"],
          ["Bookkeeper"],
          ["Budget"],
          ["Payroll"],
          ["Tax"]
        ]
      },
      {
        "category": "Product Management",
        "keywords": [
          ["Project", "Management"],
          ["Product", "Management"],
          ["Project", "Manager"],
          ["Product", "Manager"],
          ["Team", "Lead"],
          ["Scrum"],
          ["Kanban"],
          ["PM"],
          ["PMM"],
          ["CEO"],
          ["CTO"],
          ["Chief Executive Officer"],
          ["Chief Technology Officer"],
          ["R&D"]
        ]
      },
      {
        "category": "Startups",
        "keywords": []
      },
]